### ISSUE TITLE
TypeError: encode() got an unexpected keyword argument 'embedding_manager'

### ISSUE THREAD

**Issue by geox123** [hlky/sd-enable-textual-inversion#2]
![cmd_zdUvORXnlW](https://user-images.githubusercontent.com/6191801/186787013-79d2e015-3ec2-4c69-8d6b-4f5b4e52ee9c.png)

> Traceback (most recent call last):
>   File "C:\Users\George\.conda\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
>     output = await app.blocks.process_api(
>   File "C:\Users\George\.conda\envs\ldm\lib\site-packages\gradio\blocks.py", line 641, in process_api
>     predictions, duration = await self.call_function(fn_index, processed_input)
>   File "C:\Users\George\.conda\envs\ldm\lib\site-packages\gradio\blocks.py", line 554, in call_function
>     prediction = await block_fn.fn(*processed_input)
>   File "C:\Users\George\.conda\envs\ldm\lib\site-packages\gradio\interface.py", line 651, in submit_func
>     prediction = await self.run_prediction(args)
>   File "C:\Users\George\.conda\envs\ldm\lib\site-packages\gradio\interface.py", line 680, in run_prediction
>     prediction = await anyio.to_thread.run_sync(
>   File "C:\Users\George\.conda\envs\ldm\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "C:\Users\George\.conda\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>   File "C:\Users\George\.conda\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
>     result = context.run(func, *args)
>   File "scripts/webui.py", line 598, in txt2img
>     output_images, seed, info, stats = process_images(
>   File "scripts/webui.py", line 464, in process_images
>     uc = model.get_learned_conditioning(len(prompts) * [""])
>   File "c:\sd3\ldm\models\diffusion\ddpm.py", line 590, in get_learned_conditioning
>     c = self.cond_stage_model.encode(c, embedding_manager=self.embedding_manager)
> TypeError: encode() got an unexpected keyword argument 'embedding_manager'

Made completely new setup following https://rentry.org/GUItard
Loaded this embedding (bulbasaur)
[bulbasaur_embeddings_gs-1200.zip](https://github.com/hlky/sd-enable-textual-inversion/files/9428783/bulbasaur_embeddings_gs-1200.zip)

**Comment by hlky** [comment]
should be fixed [43fcd3a](https://github.com/hlky/sd-enable-textual-inversion/commit/43fcd3a3c59674566cdd82768e93401b7ff9ae7f)

**Comment by hlky** [comment]
btw do you mind if i add [bulbasaur_embeddings_gs-1200.zip](https://github.com/hlky/sd-enable-textual-inversion/files/9428783/bulbasaur_embeddings_gs-1200.zip) to [hlky/sd-embeddings](https://github.com/hlky/sd-embeddings)
do you know how many steps it was trained for?

**Comment by geox123** [comment]
> btw do you mind if i add [bulbasaur_embeddings_gs-1200.zip](https://github.com/hlky/sd-enable-textual-inversion/files/9428783/bulbasaur_embeddings_gs-1200.zip) to [hlky/sd-embeddings](https://github.com/hlky/sd-embeddings) do you know how many steps it was trained for?
[bulbasaur_embeddings_gs-3300.zip](https://github.com/hlky/sd-enable-textual-inversion/files/9433549/bulbasaur_embeddings_gs-3300.zip)
Yeah you can add it. I don't know the steps, whatever the default is from the textual_inversion repo is set to.
