### ISSUE TITLE
Add basic instructions to readme

### ISSUE THREAD

**Issue by altryne** [hlky/sd-enable-textual-inversion#6]
It would be amazing to understand which of the steps in the original textual inversion repo we should run to get this to work

**Comment by hlky** [comment]
If you're using [hlky/stable-diffusion](https://github.com/hlky/stable-diffusion) you just download this zip, drag and drop the files

**Comment by hlky** [comment]
Unless you mean the actual usage? in which case hold on ill add a bit of something
